# Generated by Django 3.2.13 on 2022-09-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220901_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritcle',
            new_name='Article',
        ),
    ]
